---
apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-actions
  labels:
    app: nrihook
data:
  setupnri: |
    #!/usr/bin/env bash
    set -x

    if ! cat /etc/containerd/config.toml | grep 'plugins."io.containerd.nri.v1.nrp"'; then
      tee -a /etc/containerd/config.toml <<EOF
    [plugins."io.containerd.nri.v1.nri"]
    disable = false
    EOF
  
    systemctl restart containerd
    fi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: &name nrihook
  labels:
    app: *name
spec:
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchFields:
              - key: metadata.name
                operator: In
                values:
                - aks-nodepool1-13823774-vmss000000
      hostPID: true
      initContainers:
      - image: docker.io/alexeldeib/nsenter-nri:latest
        name: setup-nri-idempotent-i-hope
        args: ["setupnri"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: actions
          mountPath: "/opt/actions"
        - name: hostmount
          mountPath: "/mnt/actions"
      containers:
      - image: docker.io/alexeldeib/nri-sock:latest 
        imagePullPolicy: Always
        name: injector
        command: ["/injector", "-idx", "01"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: 500Mi
        volumeMounts:
        - name: nri
          mountPath: "/var/run/nri"
          mountPropagation: Bidirectional
      - image: docker.io/alexeldeib/nri-sock:latest 
        imagePullPolicy: Always
        name: differ
        command: ["/differ", "-indices", "00,02", "-yaml"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: 500Mi
        volumeMounts:
        - name: nri
          mountPath: "/var/run/nri"
          mountPropagation: Bidirectional
      volumes:
      - name: nri
        hostPath:
          path: /var/run/nri
          type: DirectoryOrCreate
      - name: hostmount
        hostPath:
          path: /opt/actions
          type: DirectoryOrCreate
      - name: actions
        configMap:
          name: setup-actions
      terminationGracePeriodSeconds: 3
---
